# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cosmos
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation Creator With Jekyll And Markdown.Hope this little
  Description will help.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
